//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiningInfomation.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public string StudentID { get; set; }
        public string StudentName { get; set; }
        public string StudentAlias { get; set; }
        public string Password { get; set; }
        public string Team { get; set; }
        public string Motto { get; set; }
        public string TeacherID { get; set; }
        public string GroupNum { get; set; }
    
        public virtual TeacherInfo TeacherInfo { get; set; }
    }
}
