//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiningInfomation.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeacherInfo()
        {
            this.StudentInfo = new HashSet<StudentInfo>();
        }
    
        public string TeacherID { get; set; }
        public string TeacherName { get; set; }
        public string TeacherAlias { get; set; }
        public string Password { get; set; }
        public string Team { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentInfo> StudentInfo { get; set; }
    }
}
